### PR TITLE
Replace endpoint list

### PR DESCRIPTION
**Pull request by rpavlik**
Closes #84 (by replacing it).

Basically, I factored out the endpoint list into its own class that still has the same general theoretical behavior (array you can delete things out of without invalidating your place until you manually choose to compact), but keeps that behavior all centralized and outsources some to the STL.

### CODE REVIEW

**Comment by rpavlik** [comment]
As soon as travis is good with it and any desired review is done, we're good here.

**Comment by rpavlik** [comment]
Oh, yeah, and as a side effect, lots of potential null-pointer-dereferences go away as well as out-of-order null pointer checks.

**Comment by rpavlik** [comment]
Will fix the makefile and vc quick

**Comment by rpavlik** [comment]
OK, that should be better, I think - couldn't really test the vc projects well

**Comment by russell-taylor** [comment]
If this runs the logging test and the loopback test okay, I'll bet it is fine.

**Comment by rpavlik** [comment]
The logging test is the weird one that depends on the initial state, and breaks if there are files in the wrong places - it doesn't crash at any point, but it does sometimes look worse than what follows.

If these count as passes, then we should be good, since the `test_loopback` and `test_vrpn` both worked fine. The MinGW64 log below fundamentally matches the results I get from an old build I had laying around on my computer. If travis likes it, I'll merge assuming based on that comparison that I didn't break it.

The following is the execution (build by MSVC2013, in a long-used build tree) after one that said "failure" but that still said "deleting log files":

```
Sending messages to and from server with base logging only
vrpn: Connection request received from 127.0.0.1: 127.0.0.1 7100
Got text type 0 level 0: 'Server message'
Got text type 0 level 0: 'Server message'
Sending messages to and from server with client-in
vrpn: Connection request received from 127.0.0.1: 127.0.0.1 7104
vrpn_Endpoint::getOneTCPMessage:  Can't read header (this is normal when a conne
ction is dropped)
vrpn: TCP handling failed, dropping connection (this is normal when a connection
 is dropped)
Got text type 0 level 0: 'Server message'
Got text type 0 level 0: 'Server message'
Sending messages to and from server with client-out
vrpn: Connection request received from 127.0.0.1: 127.0.0.1 7106
vrpn_Endpoint::getOneTCPMessage:  Can't read header (this is normal when a conne
ction is dropped)
vrpn: TCP handling failed, dropping connection (this is normal when a connection
 is dropped)
Got text type 0 level 0: 'Server message'
Got text type 0 level 0: 'Server message'
Sending messages to and from server with server-out
vrpn: Connection request received from 127.0.0.1: 127.0.0.1 7108
vrpn_Endpoint::getOneTCPMessage:  Can't read header (this is normal when a conne
ction is dropped)
vrpn: TCP handling failed, dropping connection (this is normal when a connection
 is dropped)
vrpn_Connection::handle_log_message:  Remote connection requested logging.
Got text type 0 level 0: 'Server message'
Got text type 0 level 0: 'Server message'
Waiting for connections to close
vrpn_Endpoint::getOneTCPMessage:  Can't read header (this is normal when a conne
ction is dropped)
vrpn: TCP handling failed, dropping connection (this is normal when a connection
 is dropped)
vrpn_Endpoint::send_pending_reports(): No TCP connection
vrpn_Connection_IP::send_pending_reports:  Closing failed endpoint.
Sending messages to and from server with server-out
vrpn: Connection request received from 127.0.0.1: 127.0.0.1 7111
vrpn_Connection::handle_log_message:  Remote connection requested logging.
Got text type 0 level 0: 'Server message'
Got text type 0 level 0: 'Server message'
Testing for crash when attempt to rewrite file with client-out
vrpn_Log::open:  Log file "cli_cli_outgoing" already exists.
Writing to /tmp/vrpn_emergency_log instead.
vrpn: Connection request received from 127.0.0.1: 127.0.0.1 7113
vrpn_Endpoint::getOneTCPMessage:  Can't read header (this is normal when a conne
ction is dropped)
vrpn: TCP handling failed, dropping connection (this is normal when a connection
 is dropped)
Got text type 0 level 0: 'Server message'
Got text type 0 level 0: 'Server message'
vrpn_Log::open:  Log file "cli_cli_outgoing" already exists.
vrpn_Log::open_log:  Emergency log file "/tmp/vrpn_emergency_log" already exists
.
: No such file or directory
vrpn_Connection::vrpn_Connection:4964  Couldn't open local outgoing log file.
vrpn: Connection request received from 127.0.0.1: 127.0.0.1 7116
vrpn_Endpoint::getOneTCPMessage:  Can't read header (this is normal when a conne
ction is dropped)
vrpn: TCP handling failed, dropping connection (this is normal when a connection
 is dropped)
Got text type 0 level 0: 'Server message'
Got text type 0 level 0: 'Server message'
Waiting for connections to close
vrpn_Endpoint::getOneTCPMessage:  Can't read header (this is normal when a conne
ction is dropped)
vrpn: TCP handling failed, dropping connection (this is normal when a connection
 is dropped)
Checking for logs in Text1@file://svr_incoming-1
Got text type 0 level 0: 'Client message'
Got text type 0 level 0: 'Client message'
Checking for logs in Text0@file://svr_outgoing
Got text type 0 level 0: 'Server message'
Got text type 0 level 0: 'Server message'
Checking for logs in Text0@file://cli_cli_incoming
Got text type 0 level 0: 'Server message'
Got text type 0 level 0: 'Server message'
Checking for logs in Text1@file://cli_cli_outgoing
Got text type 0 level 0: 'Client message'
Got text type 0 level 0: 'Client message'
Got text type 0 level 0: 'Client message'
Checking for logs in Text1@file://cli_svr_incoming
Got text type 0 level 0: 'Client message'
Got text type 0 level 0: 'Client message'
Checking for logs in Text0@file://cli_svr_outgoing
Got text type 0 level 0: 'Server message'
Got text type 0 level 0: 'Server message'
Deleting log files
Success!
Press any key to continue . . .
```

and this is what I got with a brand-new fresh build tree compiling with mingw64:

```
C:\Users\Ryan\Desktop\build\vrpn-mingw64> .\server_src\test_logging.exe
Sending messages to and from server with base logging only
vrpn: Connection request received from 127.0.0.1: 127.0.0.1 7455
Got text type 0 level 0: 'Server message'
Got text type 0 level 0: 'Server message'
Sending messages to and from server with client-in
vrpn: Connection request received from 127.0.0.1: 127.0.0.1 7458
vrpn_Endpoint::getOneTCPMessage:  Can't read header (this is normal when a connection is dropped)
vrpn: TCP handling failed, dropping connection (this is normal when a connection is dropped)
Got text type 0 level 0: 'Server message'
Got text type 0 level 0: 'Server message'
Sending messages to and from server with client-out
vrpn: Connection request received from 127.0.0.1: 127.0.0.1 7461
vrpn_Endpoint::getOneTCPMessage:  Can't read header (this is normal when a connection is dropped)
vrpn: TCP handling failed, dropping connection (this is normal when a connection is dropped)
Got text type 0 level 0: 'Server message'
Got text type 0 level 0: 'Server message'
Sending messages to and from server with server-out
vrpn: Connection request received from 127.0.0.1: 127.0.0.1 7464
vrpn_Endpoint::getOneTCPMessage:  Can't read header (this is normal when a connection is dropped)
vrpn: TCP handling failed, dropping connection (this is normal when a connection is dropped)
vrpn_Connection::handle_log_message:  Remote connection requested logging.
Got text type 0 level 0: 'Server message'
Got text type 0 level 0: 'Server message'
Waiting for connections to close
vrpn_Endpoint::getOneTCPMessage:  Can't read header (this is normal when a connection is dropped)
vrpn: TCP handling failed, dropping connection (this is normal when a connection is dropped)
vrpn_Endpoint::send_pending_reports(): No TCP connection
vrpn_Connection_IP::send_pending_reports:  Closing failed endpoint.
Sending messages to and from server with server-out
vrpn: Connection request received from 127.0.0.1: 127.0.0.1 7468
vrpn_Connection::handle_log_message:  Remote connection requested logging.
Got text type 0 level 0: 'Server message'
Got text type 0 level 0: 'Server message'
Testing for crash when attempt to rewrite file with client-out
vrpn_Log::open:  Log file "cli_cli_outgoing" already exists.
Writing to /tmp/vrpn_emergency_log instead.
vrpn: Connection request received from 127.0.0.1: 127.0.0.1 7471
vrpn_Endpoint::getOneTCPMessage:  Can't read header (this is normal when a connection is dropped)
vrpn: TCP handling failed, dropping connection (this is normal when a connection is dropped)
Got text type 0 level 0: 'Server message'
Got text type 0 level 0: 'Server message'
vrpn_Log::open:  Log file "cli_cli_outgoing" already exists.
vrpn_Log::open_log:  Emergency log file "/tmp/vrpn_emergency_log" already exists.
: No error
vrpn_Connection::vrpn_Connection:4964  Couldn't open local outgoing log file.
vrpn: Connection request received from 127.0.0.1: 127.0.0.1 7476
vrpn_Endpoint::getOneTCPMessage:  Can't read header (this is normal when a connection is dropped)
vrpn: TCP handling failed, dropping connection (this is normal when a connection is dropped)
Got text type 0 level 0: 'Server message'
Got text type 0 level 0: 'Server message'
Waiting for connections to close
vrpn_Endpoint::getOneTCPMessage:  Can't read header (this is normal when a connection is dropped)
vrpn: TCP handling failed, dropping connection (this is normal when a connection is dropped)
Checking for logs in Text1@file://svr_incoming-1
Got text type 0 level 0: 'Client message'
Got text type 0 level 0: 'Client message'
Checking for logs in Text0@file://svr_outgoing
Got text type 0 level 0: 'Server message'
Got text type 0 level 0: 'Server message'
Checking for logs in Text0@file://cli_cli_incoming
Got text type 0 level 0: 'Server message'
Got text type 0 level 0: 'Server message'
Checking for logs in Text1@file://cli_cli_outgoing
Got text type 0 level 0: 'Client message'
Got text type 0 level 0: 'Client message'
Got text type 0 level 0: 'Client message'
Checking for logs in Text1@file://cli_svr_incoming
Got text type 0 level 0: 'Client message'
Got text type 0 level 0: 'Client message'
Checking for logs in Text0@file://cli_svr_outgoing
Got text type 0 level 0: 'Server message'
Got text type 0 level 0: 'Server message'
Deleting log files
Success!
```

**Pull request merged**
