### PR TITLE
Update FindOpenHaptics.cmake. Add support for newer devices

### PR DESCRIPTION
**Pull request by cyborgdennett**
https://github.com/vrpn/vrpn/issues/295

### CODE REVIEW

**Comment by cyborgdennett** [comment]
still under construction

**Comment by cyborgdennett** [comment]
Found a bug where vrpn_HapticCollision was in need of a standard init

```bash
[ 77%] Building CXX object server_src/CMakeFiles/vrpn_phantom.dir/ghostEffects/InstantBuzzEffect.cpp.o
In file included from /home/casper/dev/vrpn/server_src/ghostEffects/InstantBuzzEffect.h:17,
                 from /home/casper/dev/vrpn/server_src/ghostEffects/InstantBuzzEffect.cpp:7:
/home/casper/dev/vrpn/vrpn_Shared.h: In instantiation of ‘void vrpn_vector<T>::resize(vrpn_vector<T>::size_type) [with T = vrpn_HapticCollision; vrpn_vector<T>::size_type = long unsigned int]’:
/home/casper/dev/vrpn/vrpn_Shared.h:610:5:   required from ‘void vrpn_vector<T>::push_back(const T&) [with T = vrpn_HapticCollision]’
/home/casper/dev/vrpn/server_src/ghost.h:103:24:   required from here
/home/casper/dev/vrpn/vrpn_Shared.h:600:20: error: no matching function for call to ‘vrpn_HapticCollision::vrpn_HapticCollision()’
  600 |       T* newData = new T[s];
      |                    ^~~~~~~~
In file included from /home/casper/dev/vrpn/server_src/ghostEffects/InstantBuzzEffect.h:25,
                 from /home/casper/dev/vrpn/server_src/ghostEffects/InstantBuzzEffect.cpp:7:
```

Adding default initializer was needed
```cpp
class	vrpn_HapticCollision {
  public:
    vrpn_HapticCollision() { // this is new
      d_location = vrpn_HapticPosition(0,0,0);
      d_normal = vrpn_HapticVector(0,0,0);
    }
    vrpn_HapticCollision(const vrpn_HapticPosition &point, const vrpn_HapticVector &dir) {
      d_location = point;
      d_normal = dir;
      d_normal.normalize();
    }
```

**Comment by cyborgdennett** [comment]
Same error when doing `vrpn_print_devices Tracker0@localhost`

```
client_src/vrpn_print_devices Tracker0@localhost
Opened Tracker0@localhost as: Tracker Button Analog Dial Text.
Press ^C to exit.
VRPN Warning
 (3) from Tracker0: No response from server for >= 3 seconds
VRPN Warning
 (3) from Tracker0: No response from server for >= 3 seconds
VRPN Warning
 (3) from Tracker0: No response from server for >= 3 seconds
VRPN Warning
 (3) from Tracker0: No response from server for >= 3 seconds```

**Comment by russell-taylor** [comment]
Thank you for this pull request to make things work with newer builds!

**Pull request merged**
