### PR TITLE
Semaphore guard

### PR DESCRIPTION
**Pull request by rpavlik**
I pulled the thread and semaphore stuff into a separate file for clarity, and added an RAII-style lock/guard class for the semaphore for safety. This ensures we always unlock the semaphore when exiting scope, protecting against both coding errors (missed unlocks before return) as well as exceptions. I was able to replace almost every instance of manual locking/unlocking with the guard.

### CODE REVIEW

**Comment by russell-taylor** [comment]
I checked this against an Aqueti set of classes that use VRPN threads and semaphores, and it didn't break any of their regression tests.

**Comment by rpavlik** [comment]
So clear to merge?

**Comment by rpavlik** [comment]
Ah, rats, I missed the makefile and the visual studio manual projects

**Comment by rpavlik** [comment]
those builds got fixed after I merged #87

**Pull request merged**
