### PR TITLE
D235j update hidapi

### PR DESCRIPTION
**Pull request by rpavlik**
This is a continuation of #128 - all I did was change the `.gitmodules` file to point at the vrpn fork again since I updated it to include the latest upstream commits.

### CODE REVIEW

**Comment by rpavlik** [comment]
@russell-taylor So I think the "big scary change" here is that opening a device doesn't remove it from the enumeration on Windows. Not sure how far we depended on that behavior, since I get the impression that wasn't the case on other platforms.

**Comment by russell-taylor** [comment]
Should I go ahead and try it out with various devices and OS?

**Comment by d235j** [comment]
@russell-taylor it probably would be worth doing that. So far, behavior on Linux and Mac OS X is significantly improved, but I haven't done any testing on Windows.

**Comment by rpavlik** [comment]
Yes, please do

**Comment by russell-taylor** [comment]
On Windows, tried opening 3dConnexion Traveler, Xbox shuttle-jog 68 and raw Xbox 360 controller.  Two of them opened, but the Xkeys device complains: 

vrpn_HidInterface::reconnect(): Could not open device \\?\hid#vid_05f3&pid_045a&mi_00#7&7b36129&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}

**Comment by russell-taylor** [comment]
On Linux, all three devices report being opened.  However, the Microsoft Xbox never changes its values, just keeps reporting 0 analogs and no button responses.

This also happens on master, so looks like a new bug report rather than a reason to slow down this merge.

**Comment by d235j** [comment]
@russell-taylor how does VRPN access the Xbox 360 controller? As a maintainer of the 360Controller OS X driver we've run into many, many variants, most with different USB IDs, and some USB variation as well.

**Comment by russell-taylor** [comment]
Mac behavior is the same as the Linux behavior, except that sometimes the Xkeys also misbehaves (one time it refused to open it, sometimes it didn't report button pushes); looks like the OS is fighting for control over the device to control the scroll bars.  But the Xbox didn't ever report other than 0s (in the pull request or master).

**Comment by russell-taylor** [comment]
@d235j This is using the raw interface for a plug-in 360 controller (not wireless, not off-brand).  We've seen the differences in vendor/device ID and have separate drivers for at least three varieties.  Looks like we're not interpreting the reports right, checking into that now under a new issue.

**Comment by russell-taylor** [comment]
Any ideas on troubleshooting the Xkeys device on Windows?

**Comment by rpavlik** [comment]
Can't quite merge this yet - the failure to remove from enumeration breaks, for instance, the Hydra on Windows.

**Comment by rpavlik** [comment]
(at least in OSVR server, didn't test yet in a plain VRPN server)

**Comment by rpavlik** [comment]
Status: Looks like VRPN on its own is OK, but in context of OSVR it doesn't deal well with the Hydra on Windows. Working on improving that, this head will be rebased and force pushed a few more times.

Potential modifications found in the network in case we still have issues with some devices: 
- windows sharing, as needed for psmove apparently (thought something like this got merged at our request though...) https://github.com/hyperlogic/hidapi/commit/4dc373700dc467b36760198e75c2aad1a1f6e3ae
  - and https://github.com/signal11/hidapi/pull/44
  - and others...
- Linux hidraw (don't know how many use this vs. libusb) https://github.com/signal11/hidapi/pull/220
- Mac improvements https://github.com/signal11/hidapi/pull/40

**Comment by rpavlik** [comment]
OK, I think this is good to go - can't test with xkeys, haven't tested on Mac or with an xbox controller, but I didn't change much since those tests did take place. The changes I did make were to improve the functionality and to allow OSVR to perform autodetection of complicated VRPN-managed HID devices (particularly the Hydra) successfully. Thanks, everyone, for your testing!

**Comment by rpavlik** [comment]
Just as a follow up to this - after merging, @janoc noted some issues that resulted in the addition of some patches on top of the latest HIDAPI master, related to (what else) sharing modes on Windows, so worth re-testing the XKeys devices with the latest VRPN master to see if those updates fixed it.

I've pull requested each individual patch I made on top of HIDAPI master, though upstream has been awfully quiet.

**Comment by russell-taylor** [comment]
Tested with a new clone after this message appeared, but it still behaves as described in issue 138: https://github.com/vrpn/vrpn/issues/138

**Pull request merged**
